### ISSUE TITLE
Wpis o Stacji IT

### ISSUE THREAD

**Issue by MarcinKosinski** [whyR-conference/blog#10]
Stacja IT to inicjatywa organizowana siłami społeczności - miejsce spotkań ekspertów branżowych, profesjonalistów, którzy nieprzerwanie podnoszą swoje kompetencje, trenerów, przedsiębiorców i twórców startupów, a także osób dopiero wchodzących na rynek pracy. Dzięki unikalnemu składowi osobowemu oraz doświadczeniu partnerów, Stacja zbliża ze sobą świat biznesu, ośrodki naukowe i centra kompetencyjne, aby przekuwać wiedzę w realną wartość dla uczestników jej przedsięwzięć. Warsztaty Stacji IT gwarantują szybki start z nowymi technologiami wszystkim tym, którzy nie maja czasu samodzielnie szukać dokumentacji, przykładów, rozwiązywać podstawowych problemów i zastanawiać się nad optymalnym warsztatem. W przypadku tematów szerokich przybliżają dany obszar, pokazują wady i zalety oraz zarysowują jego złożoności. W trakcie warsztatów uczestnicy zdobywają praktyczną wiedzę z danego tematu oraz poznają najlepsze opcje dalszego rozwoju w jego obszarze. Stacja IT działa obecnie w Warszawie, Łodzi, Poznaniu, Krakowie oraz Trójmieście, wkrótce także we Wrocławiu. Jesteś ekspertem w swojej dziedzinie i chcesz poprowadzić swój własny warsztat? Zgłoś swój temat (http://www.stacja.it/#c4p), a Stacja zapewni Ci coaching trenerski oraz zajmie się kwestiami organizacyjnymi! Wydarzenia można śledzić na stronie (http://stacja.it/) Stacji IT lub meetupie (https://www.meetup.com/StacjaIT/).

**Comment by MarcinKosinski** [comment]
@agosiewska to w poniedzialek stacja ? wiecej wpisow juz nie mamyna obecna chwile

**Comment by agosiewska** [comment]
ok, będzie w poniedziałek :)
@MarcinKosinski Kogo wpisać jako autora/autorów wpisu?

**Comment by MarcinKosinski** [comment]
Dzięki
