### ISSUE TITLE
Wpis o FURBS

### ISSUE THREAD

**Issue by MarcinKosinski** [whyR-conference/blog#11]
Fundacja Rozwoju Badań Społecznych (FuRBS) to organizacja skupiona na doskonaleniu i promocji metod badań społecznych i analizy danych w życiu społeczno-gospodarczym. Dążymy do tego, by badania społeczne i analiza danych nadążały za postępem technologicznym i zmieniającymi się potrzebami społecznymi, a przy tym były dostępne i zrozumiałe dla szerokiego grona odbiorców. Prowadzimy prace badawczo-rozwojowe służące poszerzeniu stosowania badań społecznych i analizy danych w praktyce życia społecznego. Dziedziną szczególnego zainteresowania Fundacji są działania na rzecz wzrostu rangi i wykorzystywania w praktyce badań danych zastanych i metod niereaktywnych. Świadczymy również usługi konsultingu badawczego i analitycznego w dziedzinie badań naukowych, badań rynku i ewaluacji oraz usługi szkoleniowe z zakresu metod i technik badawczych, statystycznej analizy danych i obsługi narzędzi analitycznych. 

Zespół FuRBS tworzą socjologowie i psychologowie, badacze z wieloletnim doświadczeniem w badaniach społecznych, badaniach rynku i ewaluacji, jednocześnie nauczyciele akademiccy aktywni na polu dydaktycznym, badawczym i publikacyjnym.  W ciągu ostatnich dziesięciu lat eksperci Fundacji brali udział w kilkudziesięciu badaniach, analizach, ekspertyzach i ewaluacjach wykonywanych na rzecz instytucji publicznych, samorządów, NGO i przedsiębiorstw. 

Więcej informacji o FuRBS-ie znajdziecie na stronie internetowej Fundacji (http://furbs.org/) oraz Facebooku (https://www.facebook.com/FundacjaFuRBS/?fref=ts).

**Comment by MarcinKosinski** [comment]
@agosiewska jutro furbs : ) ?

**Comment by agosiewska** [comment]
tak :)

**Comment by agosiewska** [comment]
@MarcinKosinski Kogo wpisać jako autora/autorów?
